// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package coursemanagement.proxies;

public class Content implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject contentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CourseManagement.Content";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ContentTitle("ContentTitle"),
		ContentDescription("ContentDescription"),
		Content_Course("CourseManagement.Content_Course");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Content(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Content(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject contentMendixObject)
	{
		if (contentMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, contentMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.contentMendixObject = contentMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static coursemanagement.proxies.Content initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new coursemanagement.proxies.Content(context, mendixObject);
	}

	public static coursemanagement.proxies.Content load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return coursemanagement.proxies.Content.initialize(context, mendixObject);
	}

	public static java.util.List<coursemanagement.proxies.Content> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> coursemanagement.proxies.Content.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of ContentTitle
	 */
	public final java.lang.String getContentTitle()
	{
		return getContentTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of ContentTitle
	 */
	public final java.lang.String getContentTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContentTitle.toString());
	}

	/**
	 * Set value of ContentTitle
	 * @param contenttitle
	 */
	public final void setContentTitle(java.lang.String contenttitle)
	{
		setContentTitle(getContext(), contenttitle);
	}

	/**
	 * Set value of ContentTitle
	 * @param context
	 * @param contenttitle
	 */
	public final void setContentTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String contenttitle)
	{
		getMendixObject().setValue(context, MemberNames.ContentTitle.toString(), contenttitle);
	}

	/**
	 * @return value of ContentDescription
	 */
	public final java.lang.String getContentDescription()
	{
		return getContentDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of ContentDescription
	 */
	public final java.lang.String getContentDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContentDescription.toString());
	}

	/**
	 * Set value of ContentDescription
	 * @param contentdescription
	 */
	public final void setContentDescription(java.lang.String contentdescription)
	{
		setContentDescription(getContext(), contentdescription);
	}

	/**
	 * Set value of ContentDescription
	 * @param context
	 * @param contentdescription
	 */
	public final void setContentDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String contentdescription)
	{
		getMendixObject().setValue(context, MemberNames.ContentDescription.toString(), contentdescription);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Content_Course
	 */
	public final coursemanagement.proxies.Course getContent_Course() throws com.mendix.core.CoreException
	{
		return getContent_Course(getContext());
	}

	/**
	 * @param context
	 * @return value of Content_Course
	 * @throws com.mendix.core.CoreException
	 */
	public final coursemanagement.proxies.Course getContent_Course(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		coursemanagement.proxies.Course result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Content_Course.toString());
		if (identifier != null) {
			result = coursemanagement.proxies.Course.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Content_Course
	 * @param content_course
	 */
	public final void setContent_Course(coursemanagement.proxies.Course content_course)
	{
		setContent_Course(getContext(), content_course);
	}

	/**
	 * Set value of Content_Course
	 * @param context
	 * @param content_course
	 */
	public final void setContent_Course(com.mendix.systemwideinterfaces.core.IContext context, coursemanagement.proxies.Course content_course)
	{
		if (content_course == null) {
			getMendixObject().setValue(context, MemberNames.Content_Course.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Content_Course.toString(), content_course.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return contentMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final coursemanagement.proxies.Content that = (coursemanagement.proxies.Content) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
