// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package coursemanagement.proxies;

public class ContentImage extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CourseManagement.ContentImage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		EnableCaching("EnableCaching"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Content_ContentImage("CourseManagement.Content_ContentImage");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ContentImage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ContentImage(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject contentImageMendixObject)
	{
		super(context, contentImageMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, contentImageMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static coursemanagement.proxies.ContentImage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new coursemanagement.proxies.ContentImage(context, mendixObject);
	}

	public static coursemanagement.proxies.ContentImage load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return coursemanagement.proxies.ContentImage.initialize(context, mendixObject);
	}

	public static java.util.List<coursemanagement.proxies.ContentImage> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> coursemanagement.proxies.ContentImage.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Content_ContentImage
	 */
	public final coursemanagement.proxies.Content getContent_ContentImage() throws com.mendix.core.CoreException
	{
		return getContent_ContentImage(getContext());
	}

	/**
	 * @param context
	 * @return value of Content_ContentImage
	 * @throws com.mendix.core.CoreException
	 */
	public final coursemanagement.proxies.Content getContent_ContentImage(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		coursemanagement.proxies.Content result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Content_ContentImage.toString());
		if (identifier != null) {
			result = coursemanagement.proxies.Content.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Content_ContentImage
	 * @param content_contentimage
	 */
	public final void setContent_ContentImage(coursemanagement.proxies.Content content_contentimage)
	{
		setContent_ContentImage(getContext(), content_contentimage);
	}

	/**
	 * Set value of Content_ContentImage
	 * @param context
	 * @param content_contentimage
	 */
	public final void setContent_ContentImage(com.mendix.systemwideinterfaces.core.IContext context, coursemanagement.proxies.Content content_contentimage)
	{
		if (content_contentimage == null) {
			getMendixObject().setValue(context, MemberNames.Content_ContentImage.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Content_ContentImage.toString(), content_contentimage.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final coursemanagement.proxies.ContentImage that = (coursemanagement.proxies.ContentImage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
