// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package coursemanagement.proxies;

public class CourseImage extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CourseManagement.CourseImage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		EnableCaching("EnableCaching"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		CourseImage_Course("CourseManagement.CourseImage_Course");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CourseImage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CourseImage(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject courseImageMendixObject)
	{
		super(context, courseImageMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, courseImageMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static coursemanagement.proxies.CourseImage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new coursemanagement.proxies.CourseImage(context, mendixObject);
	}

	public static coursemanagement.proxies.CourseImage load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return coursemanagement.proxies.CourseImage.initialize(context, mendixObject);
	}

	public static java.util.List<coursemanagement.proxies.CourseImage> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> coursemanagement.proxies.CourseImage.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CourseImage_Course
	 */
	public final coursemanagement.proxies.Course getCourseImage_Course() throws com.mendix.core.CoreException
	{
		return getCourseImage_Course(getContext());
	}

	/**
	 * @param context
	 * @return value of CourseImage_Course
	 * @throws com.mendix.core.CoreException
	 */
	public final coursemanagement.proxies.Course getCourseImage_Course(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		coursemanagement.proxies.Course result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CourseImage_Course.toString());
		if (identifier != null) {
			result = coursemanagement.proxies.Course.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CourseImage_Course
	 * @param courseimage_course
	 */
	public final void setCourseImage_Course(coursemanagement.proxies.Course courseimage_course)
	{
		setCourseImage_Course(getContext(), courseimage_course);
	}

	/**
	 * Set value of CourseImage_Course
	 * @param context
	 * @param courseimage_course
	 */
	public final void setCourseImage_Course(com.mendix.systemwideinterfaces.core.IContext context, coursemanagement.proxies.Course courseimage_course)
	{
		if (courseimage_course == null) {
			getMendixObject().setValue(context, MemberNames.CourseImage_Course.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CourseImage_Course.toString(), courseimage_course.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final coursemanagement.proxies.CourseImage that = (coursemanagement.proxies.CourseImage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
