// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package coursemanagement.proxies;

public class CourseAssignment implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject courseAssignmentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CourseManagement.CourseAssignment";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CourseAssignment_Course("CourseManagement.CourseAssignment_Course"),
		CourseAssignment_User("CourseManagement.CourseAssignment_User");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CourseAssignment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CourseAssignment(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject courseAssignmentMendixObject)
	{
		if (courseAssignmentMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, courseAssignmentMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.courseAssignmentMendixObject = courseAssignmentMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static coursemanagement.proxies.CourseAssignment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new coursemanagement.proxies.CourseAssignment(context, mendixObject);
	}

	public static coursemanagement.proxies.CourseAssignment load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return coursemanagement.proxies.CourseAssignment.initialize(context, mendixObject);
	}

	public static java.util.List<coursemanagement.proxies.CourseAssignment> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> coursemanagement.proxies.CourseAssignment.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CourseAssignment_Course
	 */
	public final coursemanagement.proxies.Course getCourseAssignment_Course() throws com.mendix.core.CoreException
	{
		return getCourseAssignment_Course(getContext());
	}

	/**
	 * @param context
	 * @return value of CourseAssignment_Course
	 * @throws com.mendix.core.CoreException
	 */
	public final coursemanagement.proxies.Course getCourseAssignment_Course(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		coursemanagement.proxies.Course result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CourseAssignment_Course.toString());
		if (identifier != null) {
			result = coursemanagement.proxies.Course.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CourseAssignment_Course
	 * @param courseassignment_course
	 */
	public final void setCourseAssignment_Course(coursemanagement.proxies.Course courseassignment_course)
	{
		setCourseAssignment_Course(getContext(), courseassignment_course);
	}

	/**
	 * Set value of CourseAssignment_Course
	 * @param context
	 * @param courseassignment_course
	 */
	public final void setCourseAssignment_Course(com.mendix.systemwideinterfaces.core.IContext context, coursemanagement.proxies.Course courseassignment_course)
	{
		if (courseassignment_course == null) {
			getMendixObject().setValue(context, MemberNames.CourseAssignment_Course.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CourseAssignment_Course.toString(), courseassignment_course.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CourseAssignment_User
	 */
	public final usermanagement.proxies.User getCourseAssignment_User() throws com.mendix.core.CoreException
	{
		return getCourseAssignment_User(getContext());
	}

	/**
	 * @param context
	 * @return value of CourseAssignment_User
	 * @throws com.mendix.core.CoreException
	 */
	public final usermanagement.proxies.User getCourseAssignment_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		usermanagement.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CourseAssignment_User.toString());
		if (identifier != null) {
			result = usermanagement.proxies.User.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CourseAssignment_User
	 * @param courseassignment_user
	 */
	public final void setCourseAssignment_User(usermanagement.proxies.User courseassignment_user)
	{
		setCourseAssignment_User(getContext(), courseassignment_user);
	}

	/**
	 * Set value of CourseAssignment_User
	 * @param context
	 * @param courseassignment_user
	 */
	public final void setCourseAssignment_User(com.mendix.systemwideinterfaces.core.IContext context, usermanagement.proxies.User courseassignment_user)
	{
		if (courseassignment_user == null) {
			getMendixObject().setValue(context, MemberNames.CourseAssignment_User.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CourseAssignment_User.toString(), courseassignment_user.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return courseAssignmentMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final coursemanagement.proxies.CourseAssignment that = (coursemanagement.proxies.CourseAssignment) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
