// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package coursemanagement.proxies;

public class Course implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject courseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CourseManagement.Course";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Description("Description"),
		Duration("Duration"),
		TypeOfCourse("TypeOfCourse"),
		PointsForCourse("PointsForCourse"),
		StartDate("StartDate"),
		DifficultyOfCourse("DifficultyOfCourse"),
		url_course("url_course"),
		CourseImage_Course("CourseManagement.CourseImage_Course"),
		Course_User("CourseManagement.Course_User");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Course(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Course(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject courseMendixObject)
	{
		if (courseMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, courseMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.courseMendixObject = courseMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static coursemanagement.proxies.Course initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new coursemanagement.proxies.Course(context, mendixObject);
	}

	public static coursemanagement.proxies.Course load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return coursemanagement.proxies.Course.initialize(context, mendixObject);
	}

	public static java.util.List<coursemanagement.proxies.Course> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> coursemanagement.proxies.Course.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of Duration
	 */
	public final java.lang.Integer getDuration()
	{
		return getDuration(getContext());
	}

	/**
	 * @param context
	 * @return value of Duration
	 */
	public final java.lang.Integer getDuration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Duration.toString());
	}

	/**
	 * Set value of Duration
	 * @param duration
	 */
	public final void setDuration(java.lang.Integer duration)
	{
		setDuration(getContext(), duration);
	}

	/**
	 * Set value of Duration
	 * @param context
	 * @param duration
	 */
	public final void setDuration(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer duration)
	{
		getMendixObject().setValue(context, MemberNames.Duration.toString(), duration);
	}

	/**
	 * Get value of TypeOfCourse
	 * @param typeofcourse
	 */
	public final coursemanagement.proxies.ENUM_Course_TypeOfCourse getTypeOfCourse()
	{
		return getTypeOfCourse(getContext());
	}

	/**
	 * @param context
	 * @return value of TypeOfCourse
	 */
	public final coursemanagement.proxies.ENUM_Course_TypeOfCourse getTypeOfCourse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TypeOfCourse.toString());
		if (obj == null) {
			return null;
		}
		return coursemanagement.proxies.ENUM_Course_TypeOfCourse.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TypeOfCourse
	 * @param typeofcourse
	 */
	public final void setTypeOfCourse(coursemanagement.proxies.ENUM_Course_TypeOfCourse typeofcourse)
	{
		setTypeOfCourse(getContext(), typeofcourse);
	}

	/**
	 * Set value of TypeOfCourse
	 * @param context
	 * @param typeofcourse
	 */
	public final void setTypeOfCourse(com.mendix.systemwideinterfaces.core.IContext context, coursemanagement.proxies.ENUM_Course_TypeOfCourse typeofcourse)
	{
		if (typeofcourse != null) {
			getMendixObject().setValue(context, MemberNames.TypeOfCourse.toString(), typeofcourse.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.TypeOfCourse.toString(), null);
		}
	}

	/**
	 * @return value of PointsForCourse
	 */
	public final java.lang.Integer getPointsForCourse()
	{
		return getPointsForCourse(getContext());
	}

	/**
	 * @param context
	 * @return value of PointsForCourse
	 */
	public final java.lang.Integer getPointsForCourse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.PointsForCourse.toString());
	}

	/**
	 * Set value of PointsForCourse
	 * @param pointsforcourse
	 */
	public final void setPointsForCourse(java.lang.Integer pointsforcourse)
	{
		setPointsForCourse(getContext(), pointsforcourse);
	}

	/**
	 * Set value of PointsForCourse
	 * @param context
	 * @param pointsforcourse
	 */
	public final void setPointsForCourse(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer pointsforcourse)
	{
		getMendixObject().setValue(context, MemberNames.PointsForCourse.toString(), pointsforcourse);
	}

	/**
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate()
	{
		return getStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartDate.toString());
	}

	/**
	 * Set value of StartDate
	 * @param startdate
	 */
	public final void setStartDate(java.util.Date startdate)
	{
		setStartDate(getContext(), startdate);
	}

	/**
	 * Set value of StartDate
	 * @param context
	 * @param startdate
	 */
	public final void setStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date startdate)
	{
		getMendixObject().setValue(context, MemberNames.StartDate.toString(), startdate);
	}

	/**
	 * Get value of DifficultyOfCourse
	 * @param difficultyofcourse
	 */
	public final coursemanagement.proxies.ENUM_Course_Difficulty getDifficultyOfCourse()
	{
		return getDifficultyOfCourse(getContext());
	}

	/**
	 * @param context
	 * @return value of DifficultyOfCourse
	 */
	public final coursemanagement.proxies.ENUM_Course_Difficulty getDifficultyOfCourse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.DifficultyOfCourse.toString());
		if (obj == null) {
			return null;
		}
		return coursemanagement.proxies.ENUM_Course_Difficulty.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of DifficultyOfCourse
	 * @param difficultyofcourse
	 */
	public final void setDifficultyOfCourse(coursemanagement.proxies.ENUM_Course_Difficulty difficultyofcourse)
	{
		setDifficultyOfCourse(getContext(), difficultyofcourse);
	}

	/**
	 * Set value of DifficultyOfCourse
	 * @param context
	 * @param difficultyofcourse
	 */
	public final void setDifficultyOfCourse(com.mendix.systemwideinterfaces.core.IContext context, coursemanagement.proxies.ENUM_Course_Difficulty difficultyofcourse)
	{
		if (difficultyofcourse != null) {
			getMendixObject().setValue(context, MemberNames.DifficultyOfCourse.toString(), difficultyofcourse.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.DifficultyOfCourse.toString(), null);
		}
	}

	/**
	 * @return value of url_course
	 */
	public final java.lang.String geturl_course()
	{
		return geturl_course(getContext());
	}

	/**
	 * @param context
	 * @return value of url_course
	 */
	public final java.lang.String geturl_course(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.url_course.toString());
	}

	/**
	 * Set value of url_course
	 * @param url_course
	 */
	public final void seturl_course(java.lang.String url_course)
	{
		seturl_course(getContext(), url_course);
	}

	/**
	 * Set value of url_course
	 * @param context
	 * @param url_course
	 */
	public final void seturl_course(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String url_course)
	{
		getMendixObject().setValue(context, MemberNames.url_course.toString(), url_course);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CourseImage_Course
	 */
	public final coursemanagement.proxies.CourseImage getCourseImage_Course() throws com.mendix.core.CoreException
	{
		return getCourseImage_Course(getContext());
	}

	/**
	 * @param context
	 * @return value of CourseImage_Course
	 * @throws com.mendix.core.CoreException
	 */
	public final coursemanagement.proxies.CourseImage getCourseImage_Course(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		coursemanagement.proxies.CourseImage result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CourseImage_Course.toString());
		if (identifier != null) {
			result = coursemanagement.proxies.CourseImage.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CourseImage_Course
	 * @param courseimage_course
	 */
	public final void setCourseImage_Course(coursemanagement.proxies.CourseImage courseimage_course)
	{
		setCourseImage_Course(getContext(), courseimage_course);
	}

	/**
	 * Set value of CourseImage_Course
	 * @param context
	 * @param courseimage_course
	 */
	public final void setCourseImage_Course(com.mendix.systemwideinterfaces.core.IContext context, coursemanagement.proxies.CourseImage courseimage_course)
	{
		if (courseimage_course == null) {
			getMendixObject().setValue(context, MemberNames.CourseImage_Course.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CourseImage_Course.toString(), courseimage_course.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Course_User
	 */
	public final usermanagement.proxies.User getCourse_User() throws com.mendix.core.CoreException
	{
		return getCourse_User(getContext());
	}

	/**
	 * @param context
	 * @return value of Course_User
	 * @throws com.mendix.core.CoreException
	 */
	public final usermanagement.proxies.User getCourse_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		usermanagement.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Course_User.toString());
		if (identifier != null) {
			result = usermanagement.proxies.User.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Course_User
	 * @param course_user
	 */
	public final void setCourse_User(usermanagement.proxies.User course_user)
	{
		setCourse_User(getContext(), course_user);
	}

	/**
	 * Set value of Course_User
	 * @param context
	 * @param course_user
	 */
	public final void setCourse_User(com.mendix.systemwideinterfaces.core.IContext context, usermanagement.proxies.User course_user)
	{
		if (course_user == null) {
			getMendixObject().setValue(context, MemberNames.Course_User.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Course_User.toString(), course_user.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return courseMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final coursemanagement.proxies.Course that = (coursemanagement.proxies.Course) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
