// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package coursemanagement.proxies;

public class NP_CompletedContent implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject nP_CompletedContentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CourseManagement.NP_CompletedContent";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CountOfCompletedCourses("CountOfCompletedCourses");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public NP_CompletedContent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected NP_CompletedContent(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject nP_CompletedContentMendixObject)
	{
		if (nP_CompletedContentMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, nP_CompletedContentMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.nP_CompletedContentMendixObject = nP_CompletedContentMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static coursemanagement.proxies.NP_CompletedContent initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new coursemanagement.proxies.NP_CompletedContent(context, mendixObject);
	}

	public static coursemanagement.proxies.NP_CompletedContent load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return coursemanagement.proxies.NP_CompletedContent.initialize(context, mendixObject);
	}

	/**
	 * @return value of CountOfCompletedCourses
	 */
	public final java.math.BigDecimal getCountOfCompletedCourses()
	{
		return getCountOfCompletedCourses(getContext());
	}

	/**
	 * @param context
	 * @return value of CountOfCompletedCourses
	 */
	public final java.math.BigDecimal getCountOfCompletedCourses(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.CountOfCompletedCourses.toString());
	}

	/**
	 * Set value of CountOfCompletedCourses
	 * @param countofcompletedcourses
	 */
	public final void setCountOfCompletedCourses(java.math.BigDecimal countofcompletedcourses)
	{
		setCountOfCompletedCourses(getContext(), countofcompletedcourses);
	}

	/**
	 * Set value of CountOfCompletedCourses
	 * @param context
	 * @param countofcompletedcourses
	 */
	public final void setCountOfCompletedCourses(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal countofcompletedcourses)
	{
		getMendixObject().setValue(context, MemberNames.CountOfCompletedCourses.toString(), countofcompletedcourses);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return nP_CompletedContentMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final coursemanagement.proxies.NP_CompletedContent that = (coursemanagement.proxies.NP_CompletedContent) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
