// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package coursemanagement.proxies;

public class SignUpCourseTemplate implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject signUpCourseTemplateMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CourseManagement.SignUpCourseTemplate";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Username("Username"),
		CourseName("CourseName"),
		CourseLink("CourseLink");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SignUpCourseTemplate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SignUpCourseTemplate(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject signUpCourseTemplateMendixObject)
	{
		if (signUpCourseTemplateMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, signUpCourseTemplateMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.signUpCourseTemplateMendixObject = signUpCourseTemplateMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static coursemanagement.proxies.SignUpCourseTemplate initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new coursemanagement.proxies.SignUpCourseTemplate(context, mendixObject);
	}

	public static coursemanagement.proxies.SignUpCourseTemplate load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return coursemanagement.proxies.SignUpCourseTemplate.initialize(context, mendixObject);
	}

	/**
	 * @return value of Username
	 */
	public final java.lang.String getUsername()
	{
		return getUsername(getContext());
	}

	/**
	 * @param context
	 * @return value of Username
	 */
	public final java.lang.String getUsername(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Username.toString());
	}

	/**
	 * Set value of Username
	 * @param username
	 */
	public final void setUsername(java.lang.String username)
	{
		setUsername(getContext(), username);
	}

	/**
	 * Set value of Username
	 * @param context
	 * @param username
	 */
	public final void setUsername(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String username)
	{
		getMendixObject().setValue(context, MemberNames.Username.toString(), username);
	}

	/**
	 * @return value of CourseName
	 */
	public final java.lang.String getCourseName()
	{
		return getCourseName(getContext());
	}

	/**
	 * @param context
	 * @return value of CourseName
	 */
	public final java.lang.String getCourseName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CourseName.toString());
	}

	/**
	 * Set value of CourseName
	 * @param coursename
	 */
	public final void setCourseName(java.lang.String coursename)
	{
		setCourseName(getContext(), coursename);
	}

	/**
	 * Set value of CourseName
	 * @param context
	 * @param coursename
	 */
	public final void setCourseName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String coursename)
	{
		getMendixObject().setValue(context, MemberNames.CourseName.toString(), coursename);
	}

	/**
	 * @return value of CourseLink
	 */
	public final java.lang.String getCourseLink()
	{
		return getCourseLink(getContext());
	}

	/**
	 * @param context
	 * @return value of CourseLink
	 */
	public final java.lang.String getCourseLink(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CourseLink.toString());
	}

	/**
	 * Set value of CourseLink
	 * @param courselink
	 */
	public final void setCourseLink(java.lang.String courselink)
	{
		setCourseLink(getContext(), courselink);
	}

	/**
	 * Set value of CourseLink
	 * @param context
	 * @param courselink
	 */
	public final void setCourseLink(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String courselink)
	{
		getMendixObject().setValue(context, MemberNames.CourseLink.toString(), courselink);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return signUpCourseTemplateMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final coursemanagement.proxies.SignUpCourseTemplate that = (coursemanagement.proxies.SignUpCourseTemplate) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
