// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Main module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_CourseContent_Schedule_RetrieveBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Main.DS_CourseContent_Schedule_Retrieve");
		return builder;
	}

	public static java.util.List<coursemanagement.proxies.CourseAssignment> dS_CourseContent_Schedule_Retrieve(IContext context)
	{
		Object result = dS_CourseContent_Schedule_RetrieveBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> coursemanagement.proxies.CourseAssignment.initialize(context, obj));
	}
}
