// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package courseimportmidstage.proxies;

public class ContentMidPhase implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject contentMidPhaseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CourseImportMidStage.ContentMidPhase";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Number("Number"),
		ContentTitle("ContentTitle"),
		ContentDescription("ContentDescription"),
		ContentDate("ContentDate"),
		ContentNumber("ContentNumber"),
		ContentMidPhase_CourseMidPhase("CourseImportMidStage.ContentMidPhase_CourseMidPhase");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ContentMidPhase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ContentMidPhase(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject contentMidPhaseMendixObject)
	{
		if (contentMidPhaseMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, contentMidPhaseMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.contentMidPhaseMendixObject = contentMidPhaseMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static courseimportmidstage.proxies.ContentMidPhase initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new courseimportmidstage.proxies.ContentMidPhase(context, mendixObject);
	}

	public static courseimportmidstage.proxies.ContentMidPhase load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return courseimportmidstage.proxies.ContentMidPhase.initialize(context, mendixObject);
	}

	public static java.util.List<courseimportmidstage.proxies.ContentMidPhase> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> courseimportmidstage.proxies.ContentMidPhase.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Number
	 */
	public final java.lang.Integer getNumber()
	{
		return getNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Number
	 */
	public final java.lang.Integer getNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Number.toString());
	}

	/**
	 * Set value of Number
	 * @param number
	 */
	public final void setNumber(java.lang.Integer number)
	{
		setNumber(getContext(), number);
	}

	/**
	 * Set value of Number
	 * @param context
	 * @param number
	 */
	public final void setNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer number)
	{
		getMendixObject().setValue(context, MemberNames.Number.toString(), number);
	}

	/**
	 * @return value of ContentTitle
	 */
	public final java.lang.String getContentTitle()
	{
		return getContentTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of ContentTitle
	 */
	public final java.lang.String getContentTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContentTitle.toString());
	}

	/**
	 * Set value of ContentTitle
	 * @param contenttitle
	 */
	public final void setContentTitle(java.lang.String contenttitle)
	{
		setContentTitle(getContext(), contenttitle);
	}

	/**
	 * Set value of ContentTitle
	 * @param context
	 * @param contenttitle
	 */
	public final void setContentTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String contenttitle)
	{
		getMendixObject().setValue(context, MemberNames.ContentTitle.toString(), contenttitle);
	}

	/**
	 * @return value of ContentDescription
	 */
	public final java.lang.String getContentDescription()
	{
		return getContentDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of ContentDescription
	 */
	public final java.lang.String getContentDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContentDescription.toString());
	}

	/**
	 * Set value of ContentDescription
	 * @param contentdescription
	 */
	public final void setContentDescription(java.lang.String contentdescription)
	{
		setContentDescription(getContext(), contentdescription);
	}

	/**
	 * Set value of ContentDescription
	 * @param context
	 * @param contentdescription
	 */
	public final void setContentDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String contentdescription)
	{
		getMendixObject().setValue(context, MemberNames.ContentDescription.toString(), contentdescription);
	}

	/**
	 * @return value of ContentDate
	 */
	public final java.util.Date getContentDate()
	{
		return getContentDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ContentDate
	 */
	public final java.util.Date getContentDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ContentDate.toString());
	}

	/**
	 * Set value of ContentDate
	 * @param contentdate
	 */
	public final void setContentDate(java.util.Date contentdate)
	{
		setContentDate(getContext(), contentdate);
	}

	/**
	 * Set value of ContentDate
	 * @param context
	 * @param contentdate
	 */
	public final void setContentDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date contentdate)
	{
		getMendixObject().setValue(context, MemberNames.ContentDate.toString(), contentdate);
	}

	/**
	 * @return value of ContentNumber
	 */
	public final java.lang.Integer getContentNumber()
	{
		return getContentNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of ContentNumber
	 */
	public final java.lang.Integer getContentNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ContentNumber.toString());
	}

	/**
	 * Set value of ContentNumber
	 * @param contentnumber
	 */
	public final void setContentNumber(java.lang.Integer contentnumber)
	{
		setContentNumber(getContext(), contentnumber);
	}

	/**
	 * Set value of ContentNumber
	 * @param context
	 * @param contentnumber
	 */
	public final void setContentNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer contentnumber)
	{
		getMendixObject().setValue(context, MemberNames.ContentNumber.toString(), contentnumber);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ContentMidPhase_CourseMidPhase
	 */
	public final courseimportmidstage.proxies.CourseMidPhase getContentMidPhase_CourseMidPhase() throws com.mendix.core.CoreException
	{
		return getContentMidPhase_CourseMidPhase(getContext());
	}

	/**
	 * @param context
	 * @return value of ContentMidPhase_CourseMidPhase
	 * @throws com.mendix.core.CoreException
	 */
	public final courseimportmidstage.proxies.CourseMidPhase getContentMidPhase_CourseMidPhase(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		courseimportmidstage.proxies.CourseMidPhase result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ContentMidPhase_CourseMidPhase.toString());
		if (identifier != null) {
			result = courseimportmidstage.proxies.CourseMidPhase.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ContentMidPhase_CourseMidPhase
	 * @param contentmidphase_coursemidphase
	 */
	public final void setContentMidPhase_CourseMidPhase(courseimportmidstage.proxies.CourseMidPhase contentmidphase_coursemidphase)
	{
		setContentMidPhase_CourseMidPhase(getContext(), contentmidphase_coursemidphase);
	}

	/**
	 * Set value of ContentMidPhase_CourseMidPhase
	 * @param context
	 * @param contentmidphase_coursemidphase
	 */
	public final void setContentMidPhase_CourseMidPhase(com.mendix.systemwideinterfaces.core.IContext context, courseimportmidstage.proxies.CourseMidPhase contentmidphase_coursemidphase)
	{
		if (contentmidphase_coursemidphase == null) {
			getMendixObject().setValue(context, MemberNames.ContentMidPhase_CourseMidPhase.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ContentMidPhase_CourseMidPhase.toString(), contentmidphase_coursemidphase.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return contentMidPhaseMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final courseimportmidstage.proxies.ContentMidPhase that = (courseimportmidstage.proxies.ContentMidPhase) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
