// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package courseimportmidstage.proxies;

public class CourseMidPhaseImage extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CourseImportMidStage.CourseMidPhaseImage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		isSaved("isSaved"),
		PublicThumbnailPath("PublicThumbnailPath"),
		EnableCaching("EnableCaching"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		CourseMidPhaseImage_CourseMidPhase("CourseImportMidStage.CourseMidPhaseImage_CourseMidPhase");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CourseMidPhaseImage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CourseMidPhaseImage(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject courseMidPhaseImageMendixObject)
	{
		super(context, courseMidPhaseImageMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, courseMidPhaseImageMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static courseimportmidstage.proxies.CourseMidPhaseImage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new courseimportmidstage.proxies.CourseMidPhaseImage(context, mendixObject);
	}

	public static courseimportmidstage.proxies.CourseMidPhaseImage load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return courseimportmidstage.proxies.CourseMidPhaseImage.initialize(context, mendixObject);
	}

	public static java.util.List<courseimportmidstage.proxies.CourseMidPhaseImage> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> courseimportmidstage.proxies.CourseMidPhaseImage.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of isSaved
	 */
	public final java.lang.Boolean getisSaved()
	{
		return getisSaved(getContext());
	}

	/**
	 * @param context
	 * @return value of isSaved
	 */
	public final java.lang.Boolean getisSaved(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isSaved.toString());
	}

	/**
	 * Set value of isSaved
	 * @param issaved
	 */
	public final void setisSaved(java.lang.Boolean issaved)
	{
		setisSaved(getContext(), issaved);
	}

	/**
	 * Set value of isSaved
	 * @param context
	 * @param issaved
	 */
	public final void setisSaved(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean issaved)
	{
		getMendixObject().setValue(context, MemberNames.isSaved.toString(), issaved);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CourseMidPhaseImage_CourseMidPhase
	 */
	public final courseimportmidstage.proxies.CourseMidPhase getCourseMidPhaseImage_CourseMidPhase() throws com.mendix.core.CoreException
	{
		return getCourseMidPhaseImage_CourseMidPhase(getContext());
	}

	/**
	 * @param context
	 * @return value of CourseMidPhaseImage_CourseMidPhase
	 * @throws com.mendix.core.CoreException
	 */
	public final courseimportmidstage.proxies.CourseMidPhase getCourseMidPhaseImage_CourseMidPhase(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		courseimportmidstage.proxies.CourseMidPhase result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CourseMidPhaseImage_CourseMidPhase.toString());
		if (identifier != null) {
			result = courseimportmidstage.proxies.CourseMidPhase.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CourseMidPhaseImage_CourseMidPhase
	 * @param coursemidphaseimage_coursemidphase
	 */
	public final void setCourseMidPhaseImage_CourseMidPhase(courseimportmidstage.proxies.CourseMidPhase coursemidphaseimage_coursemidphase)
	{
		setCourseMidPhaseImage_CourseMidPhase(getContext(), coursemidphaseimage_coursemidphase);
	}

	/**
	 * Set value of CourseMidPhaseImage_CourseMidPhase
	 * @param context
	 * @param coursemidphaseimage_coursemidphase
	 */
	public final void setCourseMidPhaseImage_CourseMidPhase(com.mendix.systemwideinterfaces.core.IContext context, courseimportmidstage.proxies.CourseMidPhase coursemidphaseimage_coursemidphase)
	{
		if (coursemidphaseimage_coursemidphase == null) {
			getMendixObject().setValue(context, MemberNames.CourseMidPhaseImage_CourseMidPhase.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CourseMidPhaseImage_CourseMidPhase.toString(), coursemidphaseimage_coursemidphase.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final courseimportmidstage.proxies.CourseMidPhaseImage that = (courseimportmidstage.proxies.CourseMidPhaseImage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
