// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emailconfiguration.proxies;

public class EmailDetails implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject emailDetailsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EmailConfiguration.EmailDetails";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NumberOfApps("NumberOfApps");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EmailDetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EmailDetails(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject emailDetailsMendixObject)
	{
		if (emailDetailsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, emailDetailsMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.emailDetailsMendixObject = emailDetailsMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static emailconfiguration.proxies.EmailDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new emailconfiguration.proxies.EmailDetails(context, mendixObject);
	}

	public static emailconfiguration.proxies.EmailDetails load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return emailconfiguration.proxies.EmailDetails.initialize(context, mendixObject);
	}

	/**
	 * @return value of NumberOfApps
	 */
	public final java.lang.String getNumberOfApps()
	{
		return getNumberOfApps(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberOfApps
	 */
	public final java.lang.String getNumberOfApps(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NumberOfApps.toString());
	}

	/**
	 * Set value of NumberOfApps
	 * @param numberofapps
	 */
	public final void setNumberOfApps(java.lang.String numberofapps)
	{
		setNumberOfApps(getContext(), numberofapps);
	}

	/**
	 * Set value of NumberOfApps
	 * @param context
	 * @param numberofapps
	 */
	public final void setNumberOfApps(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String numberofapps)
	{
		getMendixObject().setValue(context, MemberNames.NumberOfApps.toString(), numberofapps);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return emailDetailsMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final emailconfiguration.proxies.EmailDetails that = (emailconfiguration.proxies.EmailDetails) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
