// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emailconfiguration.proxies;

public class Subscription implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject subscriptionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EmailConfiguration.Subscription";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Email("Email"),
		SubStatus("SubStatus"),
		ActiveFrom("ActiveFrom"),
		CanceledForm("CanceledForm");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Subscription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Subscription(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject subscriptionMendixObject)
	{
		if (subscriptionMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, subscriptionMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.subscriptionMendixObject = subscriptionMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static emailconfiguration.proxies.Subscription initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new emailconfiguration.proxies.Subscription(context, mendixObject);
	}

	public static emailconfiguration.proxies.Subscription load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return emailconfiguration.proxies.Subscription.initialize(context, mendixObject);
	}

	public static java.util.List<emailconfiguration.proxies.Subscription> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> emailconfiguration.proxies.Subscription.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * Get value of SubStatus
	 * @param substatus
	 */
	public final emailconfiguration.proxies.ENUM_Subscription_SubStatus getSubStatus()
	{
		return getSubStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of SubStatus
	 */
	public final emailconfiguration.proxies.ENUM_Subscription_SubStatus getSubStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.SubStatus.toString());
		if (obj == null) {
			return null;
		}
		return emailconfiguration.proxies.ENUM_Subscription_SubStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of SubStatus
	 * @param substatus
	 */
	public final void setSubStatus(emailconfiguration.proxies.ENUM_Subscription_SubStatus substatus)
	{
		setSubStatus(getContext(), substatus);
	}

	/**
	 * Set value of SubStatus
	 * @param context
	 * @param substatus
	 */
	public final void setSubStatus(com.mendix.systemwideinterfaces.core.IContext context, emailconfiguration.proxies.ENUM_Subscription_SubStatus substatus)
	{
		if (substatus != null) {
			getMendixObject().setValue(context, MemberNames.SubStatus.toString(), substatus.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.SubStatus.toString(), null);
		}
	}

	/**
	 * @return value of ActiveFrom
	 */
	public final java.util.Date getActiveFrom()
	{
		return getActiveFrom(getContext());
	}

	/**
	 * @param context
	 * @return value of ActiveFrom
	 */
	public final java.util.Date getActiveFrom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ActiveFrom.toString());
	}

	/**
	 * Set value of ActiveFrom
	 * @param activefrom
	 */
	public final void setActiveFrom(java.util.Date activefrom)
	{
		setActiveFrom(getContext(), activefrom);
	}

	/**
	 * Set value of ActiveFrom
	 * @param context
	 * @param activefrom
	 */
	public final void setActiveFrom(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date activefrom)
	{
		getMendixObject().setValue(context, MemberNames.ActiveFrom.toString(), activefrom);
	}

	/**
	 * @return value of CanceledForm
	 */
	public final java.util.Date getCanceledForm()
	{
		return getCanceledForm(getContext());
	}

	/**
	 * @param context
	 * @return value of CanceledForm
	 */
	public final java.util.Date getCanceledForm(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CanceledForm.toString());
	}

	/**
	 * Set value of CanceledForm
	 * @param canceledform
	 */
	public final void setCanceledForm(java.util.Date canceledform)
	{
		setCanceledForm(getContext(), canceledform);
	}

	/**
	 * Set value of CanceledForm
	 * @param context
	 * @param canceledform
	 */
	public final void setCanceledForm(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date canceledform)
	{
		getMendixObject().setValue(context, MemberNames.CanceledForm.toString(), canceledform);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return subscriptionMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final emailconfiguration.proxies.Subscription that = (emailconfiguration.proxies.Subscription) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
