// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excelimporter.proxies;

public enum ImportActions
{
	SynchronizeObjects(new java.lang.String[][] { new java.lang.String[] { "en_US", "Synchronize objects" }, new java.lang.String[] { "de_DE", "Objekte synchronisieren" } }),
	SynchronizeOnlyExisting(new java.lang.String[][] { new java.lang.String[] { "en_US", "Synchronize only existing objects, ignore others" }, new java.lang.String[] { "de_DE", "Synchronisiere nur existierende Objekte, ignoriere andere" } }),
	CreateObjects(new java.lang.String[][] { new java.lang.String[] { "en_US", "Create an object for each row" }, new java.lang.String[] { "de_DE", "Erstellen Sie ein Objekt für jede Zeile" } }),
	OnlyCreateNewObjects(new java.lang.String[][] { new java.lang.String[] { "en_US", "Only create not existing object" }, new java.lang.String[] { "de_DE", "Nur ein nicht vorhandenes Objekt erstellen" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ImportActions(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
