// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excelimporter.proxies;

public enum ReferenceHandlingEnum
{
	FindCreate(new java.lang.String[][] { new java.lang.String[] { "en_US", "Find reference, create if not found" }, new java.lang.String[] { "de_DE", "Referenz finden, erstellen, falls nicht gefunden" } }),
	FindIgnore(new java.lang.String[][] { new java.lang.String[] { "en_US", "Find reference, ignore if not found" }, new java.lang.String[] { "de_DE", "Referenz finden, ignorieren, falls nicht gefunden" } }),
	CreateEverything(new java.lang.String[][] { new java.lang.String[] { "en_US", "Create all referenced objects" }, new java.lang.String[] { "de_DE", "Alle referenzierten Objekte erstellen" } }),
	OnlyCreateNewObjects(new java.lang.String[][] { new java.lang.String[] { "en_US", "Only create not existing objects" }, new java.lang.String[] { "de_DE", "Nur nicht existierende Objekte erstellen" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ReferenceHandlingEnum(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
