// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excelimporter.proxies;

public enum ReferenceKeyType
{
	NoKey(new java.lang.String[][] { new java.lang.String[] { "en_US", "NoKey" }, new java.lang.String[] { "de_DE", "Kein Schlüssel" } }),
	YesOnlyAssociatedObject(new java.lang.String[][] { new java.lang.String[] { "en_US", "Yes, only for the associated object" }, new java.lang.String[] { "de_DE", "Ja, nur für das zugehörige Objekt" } }),
	YesOnlyMainObject(new java.lang.String[][] { new java.lang.String[] { "en_US", "Yes, only for the main object" }, new java.lang.String[] { "de_DE", "Ja, nur für das Hauptobjekt" } }),
	YesMainAndAssociatedObject(new java.lang.String[][] { new java.lang.String[] { "en_US", "Yes, Both for the main object and the associated object" }, new java.lang.String[] { "de_DE", "Ja, sowohl für das Hauptobjekt als auch für das zugehörige Objekt" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ReferenceKeyType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
