// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excelimporter.proxies;

public enum Status
{
	INFO(new java.lang.String[][] { new java.lang.String[] { "en_US", "INFO" }, new java.lang.String[] { "de_DE", "INFO" } }),
	VALID(new java.lang.String[][] { new java.lang.String[] { "en_US", "Valid" }, new java.lang.String[] { "de_DE", "Gültig" } }),
	INVALID(new java.lang.String[][] { new java.lang.String[] { "en_US", "INVALID" }, new java.lang.String[] { "de_DE", "UNGÜLTIG" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Status(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
