// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excelimporter.proxies;

public enum ValidationResult
{
	UnUsed(new java.lang.String[][] { new java.lang.String[] { "en_US", "UnUsed" } }),
	ValidAttribute(new java.lang.String[][] { new java.lang.String[] { "en_US", "ValidAttribute" } }),
	ValidReference(new java.lang.String[][] { new java.lang.String[] { "en_US", "ValidReference" } }),
	NoReferenceSelected(new java.lang.String[][] { new java.lang.String[] { "en_US", "NoReferenceSelected" } }),
	NoReferencedObjectSelected(new java.lang.String[][] { new java.lang.String[] { "en_US", "NoReferencedObjectSelected" } }),
	NoAttributeSelected(new java.lang.String[][] { new java.lang.String[] { "en_US", "NoAttributeSelected" } }),
	InvalidAttribute(new java.lang.String[][] { new java.lang.String[] { "en_US", "InvalidAttribute" } }),
	InvalidReference(new java.lang.String[][] { new java.lang.String[] { "en_US", "InvalidReference" } }),
	InvalidReferencedObject(new java.lang.String[][] { new java.lang.String[] { "en_US", "InvalidReferencedObject" } }),
	NoAssociationKeys(new java.lang.String[][] { new java.lang.String[] { "en_US", "No key columns for the association" } }),
	InvalidAutoNumberSelection(new java.lang.String[][] { new java.lang.String[] { "en_US", "InvalidAutoNumberSelection" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ValidationResult(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
