// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package usermanagement.proxies;

public class BGN implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject bGNMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UserManagement.BGN";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		BGN_Root("UserManagement.BGN_Root");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BGN(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected BGN(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject bGNMendixObject)
	{
		if (bGNMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, bGNMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.bGNMendixObject = bGNMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static usermanagement.proxies.BGN initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new usermanagement.proxies.BGN(context, mendixObject);
	}

	public static usermanagement.proxies.BGN load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return usermanagement.proxies.BGN.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of BGN_Root
	 */
	public final usermanagement.proxies.Root getBGN_Root() throws com.mendix.core.CoreException
	{
		return getBGN_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of BGN_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final usermanagement.proxies.Root getBGN_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		usermanagement.proxies.Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BGN_Root.toString());
		if (identifier != null) {
			result = usermanagement.proxies.Root.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of BGN_Root
	 * @param bgn_root
	 */
	public final void setBGN_Root(usermanagement.proxies.Root bgn_root)
	{
		setBGN_Root(getContext(), bgn_root);
	}

	/**
	 * Set value of BGN_Root
	 * @param context
	 * @param bgn_root
	 */
	public final void setBGN_Root(com.mendix.systemwideinterfaces.core.IContext context, usermanagement.proxies.Root bgn_root)
	{
		if (bgn_root == null) {
			getMendixObject().setValue(context, MemberNames.BGN_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.BGN_Root.toString(), bgn_root.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return bGNMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final usermanagement.proxies.BGN that = (usermanagement.proxies.BGN) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
