// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package usermanagement.proxies;

public class Capital implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject capitalMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UserManagement.Capital";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Capital_Root("UserManagement.Capital_Root"),
		Capital_JsonObject("UserManagement.Capital_JsonObject");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Capital(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Capital(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject capitalMendixObject)
	{
		if (capitalMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, capitalMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.capitalMendixObject = capitalMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static usermanagement.proxies.Capital initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new usermanagement.proxies.Capital(context, mendixObject);
	}

	public static usermanagement.proxies.Capital load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return usermanagement.proxies.Capital.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Capital_Root
	 */
	public final usermanagement.proxies.Root getCapital_Root() throws com.mendix.core.CoreException
	{
		return getCapital_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Capital_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final usermanagement.proxies.Root getCapital_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		usermanagement.proxies.Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Capital_Root.toString());
		if (identifier != null) {
			result = usermanagement.proxies.Root.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Capital_Root
	 * @param capital_root
	 */
	public final void setCapital_Root(usermanagement.proxies.Root capital_root)
	{
		setCapital_Root(getContext(), capital_root);
	}

	/**
	 * Set value of Capital_Root
	 * @param context
	 * @param capital_root
	 */
	public final void setCapital_Root(com.mendix.systemwideinterfaces.core.IContext context, usermanagement.proxies.Root capital_root)
	{
		if (capital_root == null) {
			getMendixObject().setValue(context, MemberNames.Capital_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Capital_Root.toString(), capital_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Capital_JsonObject
	 */
	public final usermanagement.proxies.JsonObject getCapital_JsonObject() throws com.mendix.core.CoreException
	{
		return getCapital_JsonObject(getContext());
	}

	/**
	 * @param context
	 * @return value of Capital_JsonObject
	 * @throws com.mendix.core.CoreException
	 */
	public final usermanagement.proxies.JsonObject getCapital_JsonObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		usermanagement.proxies.JsonObject result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Capital_JsonObject.toString());
		if (identifier != null) {
			result = usermanagement.proxies.JsonObject.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Capital_JsonObject
	 * @param capital_jsonobject
	 */
	public final void setCapital_JsonObject(usermanagement.proxies.JsonObject capital_jsonobject)
	{
		setCapital_JsonObject(getContext(), capital_jsonobject);
	}

	/**
	 * Set value of Capital_JsonObject
	 * @param context
	 * @param capital_jsonobject
	 */
	public final void setCapital_JsonObject(com.mendix.systemwideinterfaces.core.IContext context, usermanagement.proxies.JsonObject capital_jsonobject)
	{
		if (capital_jsonobject == null) {
			getMendixObject().setValue(context, MemberNames.Capital_JsonObject.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Capital_JsonObject.toString(), capital_jsonobject.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return capitalMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final usermanagement.proxies.Capital that = (usermanagement.proxies.Capital) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
