// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package usermanagement.proxies;

public class Currencies implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject currenciesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UserManagement.Currencies";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Currencies_Root("UserManagement.Currencies_Root"),
		Currencies_JsonObject("UserManagement.Currencies_JsonObject");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Currencies(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Currencies(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject currenciesMendixObject)
	{
		if (currenciesMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, currenciesMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.currenciesMendixObject = currenciesMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static usermanagement.proxies.Currencies initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new usermanagement.proxies.Currencies(context, mendixObject);
	}

	public static usermanagement.proxies.Currencies load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return usermanagement.proxies.Currencies.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Currencies_Root
	 */
	public final usermanagement.proxies.Root getCurrencies_Root() throws com.mendix.core.CoreException
	{
		return getCurrencies_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Currencies_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final usermanagement.proxies.Root getCurrencies_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		usermanagement.proxies.Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Currencies_Root.toString());
		if (identifier != null) {
			result = usermanagement.proxies.Root.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Currencies_Root
	 * @param currencies_root
	 */
	public final void setCurrencies_Root(usermanagement.proxies.Root currencies_root)
	{
		setCurrencies_Root(getContext(), currencies_root);
	}

	/**
	 * Set value of Currencies_Root
	 * @param context
	 * @param currencies_root
	 */
	public final void setCurrencies_Root(com.mendix.systemwideinterfaces.core.IContext context, usermanagement.proxies.Root currencies_root)
	{
		if (currencies_root == null) {
			getMendixObject().setValue(context, MemberNames.Currencies_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Currencies_Root.toString(), currencies_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Currencies_JsonObject
	 */
	public final usermanagement.proxies.JsonObject getCurrencies_JsonObject() throws com.mendix.core.CoreException
	{
		return getCurrencies_JsonObject(getContext());
	}

	/**
	 * @param context
	 * @return value of Currencies_JsonObject
	 * @throws com.mendix.core.CoreException
	 */
	public final usermanagement.proxies.JsonObject getCurrencies_JsonObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		usermanagement.proxies.JsonObject result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Currencies_JsonObject.toString());
		if (identifier != null) {
			result = usermanagement.proxies.JsonObject.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Currencies_JsonObject
	 * @param currencies_jsonobject
	 */
	public final void setCurrencies_JsonObject(usermanagement.proxies.JsonObject currencies_jsonobject)
	{
		setCurrencies_JsonObject(getContext(), currencies_jsonobject);
	}

	/**
	 * Set value of Currencies_JsonObject
	 * @param context
	 * @param currencies_jsonobject
	 */
	public final void setCurrencies_JsonObject(com.mendix.systemwideinterfaces.core.IContext context, usermanagement.proxies.JsonObject currencies_jsonobject)
	{
		if (currencies_jsonobject == null) {
			getMendixObject().setValue(context, MemberNames.Currencies_JsonObject.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Currencies_JsonObject.toString(), currencies_jsonobject.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return currenciesMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final usermanagement.proxies.Currencies that = (usermanagement.proxies.Currencies) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
