// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package usermanagement.proxies;

public enum ENUM_User_Departments
{
	Low_and_No_Code_Development(new java.lang.String[][] { new java.lang.String[] { "en_US", "Low and No Code Development" } }),
	Infrastructure(new java.lang.String[][] { new java.lang.String[] { "en_US", "Infrastructure" } }),
	SAP_Logistics(new java.lang.String[][] { new java.lang.String[] { "en_US", "SAP Logistics" } }),
	Java_Development(new java.lang.String[][] { new java.lang.String[] { "en_US", "Java Development" } }),
	JavaScript_Development(new java.lang.String[][] { new java.lang.String[] { "en_US", "JavaScript Development" } }),
	Mobile_Development(new java.lang.String[][] { new java.lang.String[] { "en_US", "Mobile Development" } }),
	AI_and_BI_development(new java.lang.String[][] { new java.lang.String[] { "en_US", "AI and BI development" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ENUM_User_Departments(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
