// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package usermanagement.proxies;

public class NativeName implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject nativeNameMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UserManagement.NativeName";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NativeName_Name("UserManagement.NativeName_Name"),
		Bul_NativeName("UserManagement.Bul_NativeName");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public NativeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected NativeName(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject nativeNameMendixObject)
	{
		if (nativeNameMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, nativeNameMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.nativeNameMendixObject = nativeNameMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static usermanagement.proxies.NativeName initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new usermanagement.proxies.NativeName(context, mendixObject);
	}

	public static usermanagement.proxies.NativeName load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return usermanagement.proxies.NativeName.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of NativeName_Name
	 */
	public final usermanagement.proxies.Name getNativeName_Name() throws com.mendix.core.CoreException
	{
		return getNativeName_Name(getContext());
	}

	/**
	 * @param context
	 * @return value of NativeName_Name
	 * @throws com.mendix.core.CoreException
	 */
	public final usermanagement.proxies.Name getNativeName_Name(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		usermanagement.proxies.Name result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NativeName_Name.toString());
		if (identifier != null) {
			result = usermanagement.proxies.Name.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of NativeName_Name
	 * @param nativename_name
	 */
	public final void setNativeName_Name(usermanagement.proxies.Name nativename_name)
	{
		setNativeName_Name(getContext(), nativename_name);
	}

	/**
	 * Set value of NativeName_Name
	 * @param context
	 * @param nativename_name
	 */
	public final void setNativeName_Name(com.mendix.systemwideinterfaces.core.IContext context, usermanagement.proxies.Name nativename_name)
	{
		if (nativename_name == null) {
			getMendixObject().setValue(context, MemberNames.NativeName_Name.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.NativeName_Name.toString(), nativename_name.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Bul_NativeName
	 */
	public final usermanagement.proxies.Bul getBul_NativeName() throws com.mendix.core.CoreException
	{
		return getBul_NativeName(getContext());
	}

	/**
	 * @param context
	 * @return value of Bul_NativeName
	 * @throws com.mendix.core.CoreException
	 */
	public final usermanagement.proxies.Bul getBul_NativeName(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		usermanagement.proxies.Bul result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Bul_NativeName.toString());
		if (identifier != null) {
			result = usermanagement.proxies.Bul.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Bul_NativeName
	 * @param bul_nativename
	 */
	public final void setBul_NativeName(usermanagement.proxies.Bul bul_nativename)
	{
		setBul_NativeName(getContext(), bul_nativename);
	}

	/**
	 * Set value of Bul_NativeName
	 * @param context
	 * @param bul_nativename
	 */
	public final void setBul_NativeName(com.mendix.systemwideinterfaces.core.IContext context, usermanagement.proxies.Bul bul_nativename)
	{
		if (bul_nativename == null) {
			getMendixObject().setValue(context, MemberNames.Bul_NativeName.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Bul_NativeName.toString(), bul_nativename.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return nativeNameMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final usermanagement.proxies.NativeName that = (usermanagement.proxies.NativeName) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
