// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package usermanagement.proxies;

public class Root implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject rootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UserManagement.Root";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Cca2("Cca2"),
		Flag("Flag"),
		StartOfWeek("StartOfWeek"),
		Name_Root("UserManagement.Name_Root"),
		Capital_Root("UserManagement.Capital_Root"),
		Languages_Root("UserManagement.Languages_Root"),
		Timezones_Root("UserManagement.Timezones_Root"),
		BGN_Root("UserManagement.BGN_Root"),
		Tld_Root("UserManagement.Tld_Root"),
		Currencies_Root("UserManagement.Currencies_Root");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Root(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Root(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject rootMendixObject)
	{
		if (rootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, rootMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.rootMendixObject = rootMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static usermanagement.proxies.Root initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new usermanagement.proxies.Root(context, mendixObject);
	}

	public static usermanagement.proxies.Root load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return usermanagement.proxies.Root.initialize(context, mendixObject);
	}

	/**
	 * @return value of Cca2
	 */
	public final java.lang.String getCca2()
	{
		return getCca2(getContext());
	}

	/**
	 * @param context
	 * @return value of Cca2
	 */
	public final java.lang.String getCca2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Cca2.toString());
	}

	/**
	 * Set value of Cca2
	 * @param cca2
	 */
	public final void setCca2(java.lang.String cca2)
	{
		setCca2(getContext(), cca2);
	}

	/**
	 * Set value of Cca2
	 * @param context
	 * @param cca2
	 */
	public final void setCca2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cca2)
	{
		getMendixObject().setValue(context, MemberNames.Cca2.toString(), cca2);
	}

	/**
	 * @return value of Flag
	 */
	public final java.lang.String getFlag()
	{
		return getFlag(getContext());
	}

	/**
	 * @param context
	 * @return value of Flag
	 */
	public final java.lang.String getFlag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Flag.toString());
	}

	/**
	 * Set value of Flag
	 * @param flag
	 */
	public final void setFlag(java.lang.String flag)
	{
		setFlag(getContext(), flag);
	}

	/**
	 * Set value of Flag
	 * @param context
	 * @param flag
	 */
	public final void setFlag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String flag)
	{
		getMendixObject().setValue(context, MemberNames.Flag.toString(), flag);
	}

	/**
	 * @return value of StartOfWeek
	 */
	public final java.lang.String getStartOfWeek()
	{
		return getStartOfWeek(getContext());
	}

	/**
	 * @param context
	 * @return value of StartOfWeek
	 */
	public final java.lang.String getStartOfWeek(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StartOfWeek.toString());
	}

	/**
	 * Set value of StartOfWeek
	 * @param startofweek
	 */
	public final void setStartOfWeek(java.lang.String startofweek)
	{
		setStartOfWeek(getContext(), startofweek);
	}

	/**
	 * Set value of StartOfWeek
	 * @param context
	 * @param startofweek
	 */
	public final void setStartOfWeek(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String startofweek)
	{
		getMendixObject().setValue(context, MemberNames.StartOfWeek.toString(), startofweek);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Name_Root
	 */
	public final usermanagement.proxies.Name getName_Root() throws com.mendix.core.CoreException
	{
		return getName_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Name_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final usermanagement.proxies.Name getName_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		usermanagement.proxies.Name result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Name_Root.toString());
		if (identifier != null) {
			result = usermanagement.proxies.Name.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Name_Root
	 * @param name_root
	 */
	public final void setName_Root(usermanagement.proxies.Name name_root)
	{
		setName_Root(getContext(), name_root);
	}

	/**
	 * Set value of Name_Root
	 * @param context
	 * @param name_root
	 */
	public final void setName_Root(com.mendix.systemwideinterfaces.core.IContext context, usermanagement.proxies.Name name_root)
	{
		if (name_root == null) {
			getMendixObject().setValue(context, MemberNames.Name_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Name_Root.toString(), name_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Capital_Root
	 */
	public final usermanagement.proxies.Capital getCapital_Root() throws com.mendix.core.CoreException
	{
		return getCapital_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Capital_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final usermanagement.proxies.Capital getCapital_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		usermanagement.proxies.Capital result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Capital_Root.toString());
		if (identifier != null) {
			result = usermanagement.proxies.Capital.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Capital_Root
	 * @param capital_root
	 */
	public final void setCapital_Root(usermanagement.proxies.Capital capital_root)
	{
		setCapital_Root(getContext(), capital_root);
	}

	/**
	 * Set value of Capital_Root
	 * @param context
	 * @param capital_root
	 */
	public final void setCapital_Root(com.mendix.systemwideinterfaces.core.IContext context, usermanagement.proxies.Capital capital_root)
	{
		if (capital_root == null) {
			getMendixObject().setValue(context, MemberNames.Capital_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Capital_Root.toString(), capital_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Languages_Root
	 */
	public final usermanagement.proxies.Languages getLanguages_Root() throws com.mendix.core.CoreException
	{
		return getLanguages_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Languages_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final usermanagement.proxies.Languages getLanguages_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		usermanagement.proxies.Languages result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Languages_Root.toString());
		if (identifier != null) {
			result = usermanagement.proxies.Languages.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Languages_Root
	 * @param languages_root
	 */
	public final void setLanguages_Root(usermanagement.proxies.Languages languages_root)
	{
		setLanguages_Root(getContext(), languages_root);
	}

	/**
	 * Set value of Languages_Root
	 * @param context
	 * @param languages_root
	 */
	public final void setLanguages_Root(com.mendix.systemwideinterfaces.core.IContext context, usermanagement.proxies.Languages languages_root)
	{
		if (languages_root == null) {
			getMendixObject().setValue(context, MemberNames.Languages_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Languages_Root.toString(), languages_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Timezones_Root
	 */
	public final usermanagement.proxies.Timezones getTimezones_Root() throws com.mendix.core.CoreException
	{
		return getTimezones_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Timezones_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final usermanagement.proxies.Timezones getTimezones_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		usermanagement.proxies.Timezones result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Timezones_Root.toString());
		if (identifier != null) {
			result = usermanagement.proxies.Timezones.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Timezones_Root
	 * @param timezones_root
	 */
	public final void setTimezones_Root(usermanagement.proxies.Timezones timezones_root)
	{
		setTimezones_Root(getContext(), timezones_root);
	}

	/**
	 * Set value of Timezones_Root
	 * @param context
	 * @param timezones_root
	 */
	public final void setTimezones_Root(com.mendix.systemwideinterfaces.core.IContext context, usermanagement.proxies.Timezones timezones_root)
	{
		if (timezones_root == null) {
			getMendixObject().setValue(context, MemberNames.Timezones_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Timezones_Root.toString(), timezones_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of BGN_Root
	 */
	public final usermanagement.proxies.BGN getBGN_Root() throws com.mendix.core.CoreException
	{
		return getBGN_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of BGN_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final usermanagement.proxies.BGN getBGN_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		usermanagement.proxies.BGN result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BGN_Root.toString());
		if (identifier != null) {
			result = usermanagement.proxies.BGN.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of BGN_Root
	 * @param bgn_root
	 */
	public final void setBGN_Root(usermanagement.proxies.BGN bgn_root)
	{
		setBGN_Root(getContext(), bgn_root);
	}

	/**
	 * Set value of BGN_Root
	 * @param context
	 * @param bgn_root
	 */
	public final void setBGN_Root(com.mendix.systemwideinterfaces.core.IContext context, usermanagement.proxies.BGN bgn_root)
	{
		if (bgn_root == null) {
			getMendixObject().setValue(context, MemberNames.BGN_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.BGN_Root.toString(), bgn_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Tld_Root
	 */
	public final usermanagement.proxies.Tld getTld_Root() throws com.mendix.core.CoreException
	{
		return getTld_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Tld_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final usermanagement.proxies.Tld getTld_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		usermanagement.proxies.Tld result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Tld_Root.toString());
		if (identifier != null) {
			result = usermanagement.proxies.Tld.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Tld_Root
	 * @param tld_root
	 */
	public final void setTld_Root(usermanagement.proxies.Tld tld_root)
	{
		setTld_Root(getContext(), tld_root);
	}

	/**
	 * Set value of Tld_Root
	 * @param context
	 * @param tld_root
	 */
	public final void setTld_Root(com.mendix.systemwideinterfaces.core.IContext context, usermanagement.proxies.Tld tld_root)
	{
		if (tld_root == null) {
			getMendixObject().setValue(context, MemberNames.Tld_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Tld_Root.toString(), tld_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Currencies_Root
	 */
	public final usermanagement.proxies.Currencies getCurrencies_Root() throws com.mendix.core.CoreException
	{
		return getCurrencies_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Currencies_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final usermanagement.proxies.Currencies getCurrencies_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		usermanagement.proxies.Currencies result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Currencies_Root.toString());
		if (identifier != null) {
			result = usermanagement.proxies.Currencies.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Currencies_Root
	 * @param currencies_root
	 */
	public final void setCurrencies_Root(usermanagement.proxies.Currencies currencies_root)
	{
		setCurrencies_Root(getContext(), currencies_root);
	}

	/**
	 * Set value of Currencies_Root
	 * @param context
	 * @param currencies_root
	 */
	public final void setCurrencies_Root(com.mendix.systemwideinterfaces.core.IContext context, usermanagement.proxies.Currencies currencies_root)
	{
		if (currencies_root == null) {
			getMendixObject().setValue(context, MemberNames.Currencies_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Currencies_Root.toString(), currencies_root.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return rootMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final usermanagement.proxies.Root that = (usermanagement.proxies.Root) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
