// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package usermanagement.proxies;

public class Tld implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject tldMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UserManagement.Tld";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Tld_Root("UserManagement.Tld_Root"),
		Tld_JsonObject("UserManagement.Tld_JsonObject");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Tld(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Tld(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject tldMendixObject)
	{
		if (tldMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, tldMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.tldMendixObject = tldMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static usermanagement.proxies.Tld initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new usermanagement.proxies.Tld(context, mendixObject);
	}

	public static usermanagement.proxies.Tld load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return usermanagement.proxies.Tld.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Tld_Root
	 */
	public final usermanagement.proxies.Root getTld_Root() throws com.mendix.core.CoreException
	{
		return getTld_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Tld_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final usermanagement.proxies.Root getTld_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		usermanagement.proxies.Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Tld_Root.toString());
		if (identifier != null) {
			result = usermanagement.proxies.Root.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Tld_Root
	 * @param tld_root
	 */
	public final void setTld_Root(usermanagement.proxies.Root tld_root)
	{
		setTld_Root(getContext(), tld_root);
	}

	/**
	 * Set value of Tld_Root
	 * @param context
	 * @param tld_root
	 */
	public final void setTld_Root(com.mendix.systemwideinterfaces.core.IContext context, usermanagement.proxies.Root tld_root)
	{
		if (tld_root == null) {
			getMendixObject().setValue(context, MemberNames.Tld_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Tld_Root.toString(), tld_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Tld_JsonObject
	 */
	public final usermanagement.proxies.JsonObject getTld_JsonObject() throws com.mendix.core.CoreException
	{
		return getTld_JsonObject(getContext());
	}

	/**
	 * @param context
	 * @return value of Tld_JsonObject
	 * @throws com.mendix.core.CoreException
	 */
	public final usermanagement.proxies.JsonObject getTld_JsonObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		usermanagement.proxies.JsonObject result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Tld_JsonObject.toString());
		if (identifier != null) {
			result = usermanagement.proxies.JsonObject.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Tld_JsonObject
	 * @param tld_jsonobject
	 */
	public final void setTld_JsonObject(usermanagement.proxies.JsonObject tld_jsonobject)
	{
		setTld_JsonObject(getContext(), tld_jsonobject);
	}

	/**
	 * Set value of Tld_JsonObject
	 * @param context
	 * @param tld_jsonobject
	 */
	public final void setTld_JsonObject(com.mendix.systemwideinterfaces.core.IContext context, usermanagement.proxies.JsonObject tld_jsonobject)
	{
		if (tld_jsonobject == null) {
			getMendixObject().setValue(context, MemberNames.Tld_JsonObject.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Tld_JsonObject.toString(), tld_jsonobject.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return tldMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final usermanagement.proxies.Tld that = (usermanagement.proxies.Tld) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
