// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package coursemanagement.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the CourseManagement module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Content_SaveBuilder(
		coursemanagement.proxies.Content _content,
		coursemanagement.proxies.Course _course
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CourseManagement.ACT_Content_Save");
		builder = builder.withParam("Content", _content);
		builder = builder.withParam("Course", _course);
		return builder;
	}

	public static void aCT_Content_Save(
		IContext context,
		coursemanagement.proxies.Content _content,
		coursemanagement.proxies.Course _course
	)
	{
		aCT_Content_SaveBuilder(
				_content,
				_course
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Course_SaveBuilder(
		coursemanagement.proxies.Course _course
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CourseManagement.ACT_Course_Save");
		builder = builder.withParam("Course", _course);
		return builder;
	}

	public static void aCT_Course_Save(
		IContext context,
		coursemanagement.proxies.Course _course
	)
	{
		aCT_Course_SaveBuilder(
				_course
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_CourseImage_UploadBuilder(
		coursemanagement.proxies.CourseImage _courseImage,
		coursemanagement.proxies.Course _course
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CourseManagement.ACT_CourseImage_Upload");
		builder = builder.withParam("CourseImage", _courseImage);
		builder = builder.withParam("Course", _course);
		return builder;
	}

	public static void aCT_CourseImage_Upload(
		IContext context,
		coursemanagement.proxies.CourseImage _courseImage,
		coursemanagement.proxies.Course _course
	)
	{
		aCT_CourseImage_UploadBuilder(
				_courseImage,
				_course
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder vAL_Content_FieldValidationBuilder(
		coursemanagement.proxies.Content _content
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CourseManagement.VAL_Content_FieldValidation");
		builder = builder.withParam("Content", _content);
		return builder;
	}

	public static boolean vAL_Content_FieldValidation(
		IContext context,
		coursemanagement.proxies.Content _content
	)
	{
		Object result = vAL_Content_FieldValidationBuilder(
				_content
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder vAL_Course_FieldValidationBuilder(
		coursemanagement.proxies.Course _course
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CourseManagement.VAL_Course_FieldValidation");
		builder = builder.withParam("Course", _course);
		return builder;
	}

	public static boolean vAL_Course_FieldValidation(
		IContext context,
		coursemanagement.proxies.Course _course
	)
	{
		Object result = vAL_Course_FieldValidationBuilder(
				_course
			)
			.execute(context);
		return (boolean) result;
	}
}
