// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package notifications.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Notifications module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sample_ACT_CreateEmailFromTemplateAndThenSend_2Builder(
		usermanagement.proxies.User _user,
		email_connector.proxies.EmailTemplate _emailTemplate
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Notifications.Sample_ACT_CreateEmailFromTemplateAndThenSend_2");
		builder = builder.withParam("User", _user);
		builder = builder.withParam("EmailTemplate", _emailTemplate);
		return builder;
	}

	public static void sample_ACT_CreateEmailFromTemplateAndThenSend_2(
		IContext context,
		usermanagement.proxies.User _user,
		email_connector.proxies.EmailTemplate _emailTemplate
	)
	{
		sample_ACT_CreateEmailFromTemplateAndThenSend_2Builder(
				_user,
				_emailTemplate
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sample_ACT_SendEmailWithTemplate_2Builder(
		email_connector.proxies.EmailAccount _emailAccountAsDataObject,
		email_connector.proxies.EmailTemplate _emailTemplate
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Notifications.Sample_ACT_SendEmailWithTemplate_2");
		builder = builder.withParam("EmailAccountAsDataObject", _emailAccountAsDataObject);
		builder = builder.withParam("EmailTemplate", _emailTemplate);
		return builder;
	}

	public static void sample_ACT_SendEmailWithTemplate_2(
		IContext context,
		email_connector.proxies.EmailAccount _emailAccountAsDataObject,
		email_connector.proxies.EmailTemplate _emailTemplate
	)
	{
		sample_ACT_SendEmailWithTemplate_2Builder(
				_emailAccountAsDataObject,
				_emailTemplate
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sample_ASU_SubscribeForEmailNotification_2Builder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Notifications.Sample_ASU_SubscribeForEmailNotification_2");
		return builder;
	}

	public static boolean sample_ASU_SubscribeForEmailNotification_2(IContext context)
	{
		Object result = sample_ASU_SubscribeForEmailNotification_2Builder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_GetSystemError_2Builder(
		system.proxies.Error _systemErrObj
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Notifications.SUB_GetSystemError_2");
		builder = builder.withParam("SystemErrObj", _systemErrObj);
		return builder;
	}

	public static java.lang.String sUB_GetSystemError_2(
		IContext context,
		system.proxies.Error _systemErrObj
	)
	{
		Object result = sUB_GetSystemError_2Builder(
				_systemErrObj
			)
			.execute(context);
		return (java.lang.String) result;
	}
}
