// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package notifications.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Notifications module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Email_SendEmailForAssignedCourseBuilder(
		coursemanagement.proxies.CourseAssignment _courseAssignment
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Notifications.ACT_Email_SendEmailForAssignedCourse");
		builder = builder.withParam("CourseAssignment", _courseAssignment);
		return builder;
	}

	public static void aCT_Email_SendEmailForAssignedCourse(
		IContext context,
		coursemanagement.proxies.CourseAssignment _courseAssignment
	)
	{
		aCT_Email_SendEmailForAssignedCourseBuilder(
				_courseAssignment
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Email_SendEmailForNewAccountBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Notifications.ACT_Email_SendEmailForNewAccount");
		return builder;
	}

	public static void aCT_Email_SendEmailForNewAccount(IContext context)
	{
		aCT_Email_SendEmailForNewAccountBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Email_SendEmailForSignUpCourseBuilder(
		coursemanagement.proxies.CourseAssignment _courseAssignment
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Notifications.ACT_Email_SendEmailForSignUpCourse");
		builder = builder.withParam("CourseAssignment", _courseAssignment);
		return builder;
	}

	public static void aCT_Email_SendEmailForSignUpCourse(
		IContext context,
		coursemanagement.proxies.CourseAssignment _courseAssignment
	)
	{
		aCT_Email_SendEmailForSignUpCourseBuilder(
				_courseAssignment
			)
			.execute(context);
	}
}
