// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package atlas_core.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Atlas_Core module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_User_RetrieveBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_Core.DS_User_Retrieve");
		return builder;
	}

	public static usermanagement.proxies.User dS_User_Retrieve(IContext context)
	{
		Object result = dS_User_RetrieveBuilder().execute(context);
		return result == null ? null : usermanagement.proxies.User.initialize(context, (IMendixObject) result);
	}
}
